gtnh.settings.blowdryerTag = 0.2.2
modName = TCost
modId = tcost
modGroup = io.github.thecakeisalie05.tcost
useModGroupForPublishing = true
autoUpdateBuildScript = false
minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614
channel = stable
mappingsVersion = 12
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/
developmentEnvironmentUserName = Cake
enableModernJavaSyntax = jabel
enableGenericInjection = true
generateGradleTokenClass = io.github.thecakeisalie05.tcost.Tags
gradleTokenVersion = VERSION
replaceGradleTokenInFile =
apiPackage =
accessTransformersFile =
usesMixins = false
separateMixinSourceSet =
usesMixinDebug = false
mixinPlugin =
mixinsPackage =
coreModClass =
containsMixinsAndOrCoreModOnly = false
forceEnableMixins = false
usesShadowedDependencies = false
minimizeShadowedDependencies = true
relocateShadowedDependencies = true
includeWellKnownRepositories = true
excludeWellKnownRepositories =
usesMavenPublishing = false
modrinthProjectId =
modrinthRelations =
curseForgeProjectId =
curseForgeEnvironments = client
curseForgeRelations =
disableSpotless = true
disableCheckstyle = true
org.gradle.configuration-cache = true
org.gradle.parallel = true
